#FROM clojure:tools-deps-1.10.1.727-slim-buster AS builder
#FROM clojure:tools-deps-1.11.1.1257 AS builder
FROM clojure AS builder

RUN apt-get update
RUN apt-get upgrade --yes
RUN apt-get install -y curl
#RUN apt-get install software-properties-common
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y git
RUN apt-get install -y zip
RUN mkdir -p /usr/share/man/man1
RUN apt-get install -y maven
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN apt-get update; apt-get install -y python3-pip
RUN python3 -m pip install requests --break-system-packages
RUN python3 -m pip install pyparsing --break-system-packages
RUN python3 -m pip install fsst --break-system-packages

RUN mkdir -p /usr/src/fluree-ledger
WORKDIR /usr/src/fluree-ledger


COPY git_clone_fluree_latest.py /usr/src/git_clone_fluree_latest.py
RUN ../git_clone_fluree_latest.py
COPY fluree_version_patch.py /usr/src/fluree-ledger
RUN python3 ./fluree_version_patch.py
RUN clojure -A:test -Stree
RUN make

FROM python:3.9-slim-buster AS runner
WORKDIR /usr/src/fsst

COPY --from=builder /usr/src/fluree-ledger/build/fluree-*.zip /usr/src/
COPY git_info_fluree_latest.py /usr/src/fsst/git_info_fluree_latest.py
RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get --yes install apt-utils && \
    apt-get install --yes gcc && \
    apt-get install --yes g++ && \
    # Some extra dependencies needed because we use the "slim" python image from docker.
    apt-get --yes install libgmp-dev && \
    apt-get --yes install unzip && \
    apt-get install dialog -y && \
    # Install Java (dependency for FlureeDB)
    apt-get install openjdk-11-jre-headless -y && \
    # Get the latest pip for the 3.9 version of Python
    python3 -m pip install pip --force && \
    # Dependencies of fsst tool
    python3 -m pip install fsst[domainapi] && \
    # Unzip the fluree zip file and remove the zip.
    cd /usr/src && \
    unzip fluree-*.zip -d fsst/ && \
    python3 /usr/src/fsst/git_info_fluree_latest.py >> VERSION && \
    rm fluree-*.zip && \
    # Remove stuff we no longer need.
    apt autoremove --yes && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["/usr/src/fsst/fluree_start.sh"]
